apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  # storageClassName: "standard"
  # for eks
  storageClassName: gp2
  volumeName: gp2-pv