services:
  my-app:
    image: shashkist/flask-contacts-app:1.4
    container_name: my-app-mysql
    ports:
      - 5054:5052
    environment:
      - DATABASE_TYPE=MYSQL
      - DB_HOST=mysql
      - DB_PORT=3306
      # - MONGO_URI=mongodb://mongo:27017
  
  mysql:
    image: mysql
    # ports:
      # - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - sql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 5012:80
    environment:
      - PMA_HOST=mysql
volumes:
  sql-data:

