services:
  my-app:
    image: shashkist/flask-contacts-app:1.4
    # image: shashkist/flask_contacts_course
    container_name: my-app-mysql
    ports:
      - "5054:5052"
    environment:
      - DATABASE_TYPE=MYSQL
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - sql-data:/var/lib/mysql
    healthcheck:      
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "5012:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  sql-data: