services:
  my-app:
    build: .
    image: shashkist/flask-contacts-app:1.4
    container_name: my-app-mongo
    ports:
      - 5053:5052
    environment:
      - DATABASE_TYPE=MONGO
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
  
  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=admin
  
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "admin", "--eval", "db.stats()"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    # environment:
    #   - PMA_HOST=mysql
    depends_on:
      mongo:
        condition: service_healthy
   
volumes:
  mongo-data:


