customLabels: {}

dnsConfig: {}

env: {}

extraArgs:
  - --collect-all

fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: percona/mongodb_exporter
  tag: ""

imagePullSecrets: []

livenessProbe:
  httpGet:
    path: /
    port: metrics
  initialDelaySeconds: 10

mongodb:
  uri: "mongodb://mongo-service:27017"

existingSecret:
  name: ""
  key: "mongodb-uri"
