apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-contacts-app
  labels:
    app: flask-contacts-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-contacts-app
  template:
    metadata:
      labels:
        app: flask-contacts-app
    spec:
      containers:
      - name: flask-contacts-app
        image: shashkist/flask-contacts-app:1.4
        ports:
        - containerPort: 5052
        env:
        - name: DATABASE_TYPE
          valueFrom:
            configMapKeyRef:
              name: flask-mongo-config
              key: db_type
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: flask-mongo-config
              key: mongo_url
---
apiVersion: v1
kind: Service
metadata:
  name: flask-contacts-app-service
  labels:
    app: flask-contacts-service # this should be mapped by service monitor
spec:
  selector:
    app: flask-contacts-app
  type: LoadBalancer  
  ports:
    - name: flask-contacts-service #this port name should be mapped by service monitor
      protocol: TCP
      port: 5053
      targetPort: 5052
       
