apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 423623847692.dkr.ecr.eu-north-1.amazonaws.com/finaldevop/dugems:latest
        ports:
        - containerPort: 5000  # Make sure this matches your Flask app's port
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "production"
