apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    targetPort: http
    name: http
  selector:
    app: prometheus
  type: ClusterIP
