apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/rules/*.rules
    scrape_configs:
      - job_name: 'jenkins'
        metrics_path: /prometheus
        static_configs:
          - targets: ['jenkins:8080']
      - job_name: 'application'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: my-app
            action: keep
