apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-files-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /minikube-host/C/Users/Iliap/static-images
   