customRules:
  flask_service_alerts:
    groups:
      - name: flask_service_alerts
        rules:
          - alert: FlaskServiceDown
            expr: up{service="flask-contacts-app-service"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Flask Service is Down"
              description: "The Flask service (flask-contacts-app-service) is not responding for more than 1 minute."
prometheus:
  prometheusSpec:
    ruleSelector:
      matchLabels:
        prometheus: flask-service-alerts
